# ==========================================
# PHẦN 1: TỪ ĐIỂN ID -> TÊN (Chính xác nhất)
# Dùng để kiểm tra ID này là map nào
# ==========================================

MAP_ID_TO_NAME = {
    0: "Làng Aru",
    1: "Đồi hoa cúc",
    2: "Thung lũng tre",
    3: "Rừng nấm",
    4: "Rừng xương",
    5: "Đảo Kamê",
    6: "Đông Karin",
    7: "Làng Mori",
    8: "Đồi nấm tím",
    9: "Thị trấn Moori",
    10: "Thung lũng Namếc",
    11: "Thung lũng Maima",
    12: "Vực maima",
    13: "Đảo Guru",
    14: "Làng Kakarot",
    15: "Đồi hoang",
    16: "Làng Plant",
    17: "Rừng nguyên sinh",
    18: "Rừng thông Xayda",
    19: "Thành phố Vegeta",
    20: "Vách núi đen",
    21: "Nhà Gôhan",
    22: "Nhà Moori",
    23: "Nhà Broly",
    24: "Trạm tàu vũ trụ - trái đất",
    25: "Trạm tàu vũ trụ - xayza",
    26: "Trạm tàu vũ trụ - namex",
    27: "Rừng Bamboo",
    28: "Rừng dương xỉ",
    29: "Nam Kamê",
    30: "Đảo Bulông",
    31: "Núi hoa vàng",
    32: "Núi hoa tím",
    33: "Nam Guru",
    34: "Đông Nam Guru",
    35: "Rừng cọ",
    36: "Rừng đá",
    37: "Thung lũng đen",
    38: "Bờ vực đen",
    39: "Vách núi Aru",
    40: "Vách núi Moori",
    41: "Vực Plant",
    42: "Vách núi Aru",
    43: "Vách núi Moori",
    44: "Vách núi Kakarot",
    45: "Thần điện",
    46: "Tháp Karin",
    47: "Rừng Karin",
    48: "Hành tinh Kaio",
    49: "Phòng tập thời gian",
    50: "Thánh địa Kaio",
    51: "Đấu trường",
    52: "Đại hội võ thuật",
    53: "Tường thành 1",
    54: "Tầng 3",
    55: "Tầng 1",
    56: "Tầng 2",
    57: "Tầng 4",
    58: "Tường thành 2",
    59: "Tường thành 3",
    60: "Trại độc nhãn 1",
    61: "Trại độc nhãn 2",
    62: "Trại độc nhãn 3",
    63: "Trại lính Fide",
    64: "Núi dây leo",
    65: "Núi cây quỷ",
    66: "Trại quỷ già",
    67: "Mê Cung Chết Chóc",#Vực chết",
    68: "Thung lũng Nappa",
    69: "Vực cấm",
    70: "Núi Appule",
    71: "Căn cứ Raspberry",
    72: "Thung lũng Raspberry",
    73: "Thung lũng chết",
    74: "Đồi cây Fide",
    75: "Khe núi tử thần",
    76: "Núi đá",
    77: "Rừng đá",
    78: "Lãnh  địa Fize",
    79: "Núi khỉ đỏ",
    80: "Núi khỉ vàng",
    81: "Hang quỷ chim",
    82: "Núi khỉ đen",
    83: "Hang khỉ đen",
    84: "Siêu Thị",
    85: "Hành tinh M-2",
    86: "Hành tinh Polaris",
    87: "Hành tinh Cretaceous",
    88: "Hành tinh Monmaasu",
    89: "Hành tinh Rudeeze",
    90: "Hành tinh Gelbo",
    91: "Hành tinh Tigere",
    92: "Thành phố phía đông",
    93: "Thành phố phía nam",
    94: "Đảo Balê",
    95: "95",
    96: "Cao nguyên",
    97: "Thành phố phía bắc",
    98: "Ngọn núi phía bắc",
    99: "Thung lũng phía bắc",
    100: "Thị trấn Ginder",
    101: "101",
    102: "Nhà Bunma",
    103: "Võ đài Xên bọ hung",
    104: "Sân sau siêu thị",
    105: "Cánh đồng tuyết",
    106: "Rừng tuyết",
    107: "Núi tuyết",
    108: "Dòng sông băng",
    109: "Rừng băng",
    110: "Hang băng",
    111: "Đông Nam Karin",
    112: "Võ đài Hạt Mít",
    113: "Đại hội võ thuật",
    114: "Cổng phi thuyền",
    115: "Phòng chờ",
    116: "Thánh địa Kaio",
    117: "Cửa Ải 1",
    118: "Cửa Ải 2",
    119: "Cửa Ải 3",
    120: "Phòng chỉ huy",
    121: "Đấu trường",
    122: "Ngũ Hành Sơn 2",
    123: "Ngũ Hành Sơn 1",
    124: "Ngũ Hành Sơn 3",
    125: "Võ đài Bang",
    126: "Thành phố Santa",
    127: "Cổng phi thuyền",
    128: "Bụng Mabư",
    129: "Đại hội võ thuật",
    130: "Đại hội võ thuật Vũ Trụ",
    131: "Hành Tinh Yardart",
    132: "Hành Tinh Yardart 2",
    133: "Hành Tinh Yardart 3",
    134: "Đại hội võ thuật Vũ Trụ 6-7",
    135: "Động hải tặc",
    136: "Hang Bạch Tuộc",
    137: "Động kho báu",
    138: "Cảng hải tặc",
    139: "Hành tinh Potaufeu",
    140: "Hang động Potaufeu",
    141: "Con đường rắn độc",
    142: "Con đường rắn độc",
    143: "Con đường rắn độc",
    144: "Hoang mạc",
    145: "Võ Đài Siêu Cấp",
    146: "Tây Karin",
    147: "Sa mạc",
    148: "Lâu đài Lychee",
    149: "Thành phố Santa",
    150: "Lôi Đài",
    151: "Hành tinh bóng tối",
    152: "Vùng đất băng giá",
    153: "Lãnh địa bang hội",
    154: "Hành tinh Bill",
    155: "Hành tinh ngục tù",
    156: "Tây thánh địa",
    157: "Đông thánh Địa",
    158: "Bắc thánh địa",
    159: "Nam thánh Địa",
    160: "Khu hang động",
    161: "Bìa rừng nguyên thủy",
    162: "Rừng nguyên thủy",
    163: "Làng Plant nguyên thủy",
    164: "Tranh ngọc Namếc",
    165: "Map Boss",
    166: "Hành tinh ngục tù",
    167: "Địa ngục tầng 1",
    168: "Địa ngục tầng 2",
    169: "Địa ngục tầng 3",
    170: "Phòng tập thời gian",
    171: "Địa ngục tầng 4",
    172: "Phòng chờ thời gian",
    173: "Cánh đồng tuyết 2",
    174: "Rừng tuyết 2",
    175: "Hang băng 2",
    176: "NEW Nam Kamê",
    177: "Rừng nguyên sinh",
    178: "Ngọn núi phía bắc",
    179: "Phòng thí nghiệm Myuu",
    180: "Mù căng chải",
    181: "Sa mạc hoang vu"
}



# ==========================================
# PHẦN 2: TỪ ĐIỂN TÊN -> ID (Tự động sinh)
# Mapping Name -> ID được tạo tự động từ danh sách trên.
# Nếu có trùng tên, ID lớn hơn (xuất hiện sau) sẽ được ưu tiên.
# ==========================================

MAP_NAME_TO_ID = {}
for map_id, map_name in MAP_ID_TO_NAME.items():
    MAP_NAME_TO_ID[map_name] = map_id

# Bổ sung/Override thủ công nếu cần (Alias, Shortcut...)
# MAP_NAME_TO_ID["Tên Khác"] = ID